### ISSUE TITLE
Failures with pandas 23.4

### ISSUE THREAD

**Issue by sarahlarocca** [Dirguis/ipfn#13]
I am experiencing a similar problem to that described here when using ipfn:

https://stackoverflow.com/questions/51979146/cannot-set-using-loc-with-a-string-labelled-index

**Comment by Dirguis** [comment]
Hello,

Sorry, I did not see the messages, my notifications were turned off.
I just released another version 1.3.0, that takes into account that issue with pandas. You can upgrade the code like so:
`
pip install --user --upgrade ipfn
`

I don't really know why Pandas is throwing that error, and it does so only when the marginals are of one dimensions. 2 seems to be fine. So when the marginal is of dimension 1, I use a mask, otherwise, I  kept the code as is.

In addition, I added a test section in case people want to modify the code but still want to check that all is fine.

Finally, note that the pandas version, although convenient, is very time consuming. It is ok for small problems. If you have big problems (several thousands marginals for example), you will be better off with the numpy version.

Cheers and thanks for checking the code out!
